gText_Birch_Welcome::
	.string "Hey, da quanto tempo...\n"
	.string "allora come vi va?\p"
	.string "Sai tempo fa è passato Fuso...\n"
    .string "è da un pò che non lo vedevo.\p"
	.string "Ah si, qui il maschile e femminile\n"
    .string "è un pò misto, quindi...\p$"

gText_Birch_Pokemon::
    .string "Sai Anni fa... Era Notte\n"
    .string "C'eravamo io, Fuso, Tha e Vasco.\p"
	.string "In un vicolo... ci stavamo\n"
    .string "facendo in vena, Musica...\p"
	.string "e niente la solitudine dei tossici.\n"
	.string "A un certa Vasco fa tipo...\p"
	.string "Eh Eh, l'inchiostro per la penna\n"
    .string "è come l'azzurro per il cielo\p"
    .string "quando il sole si va a fare la luna.\n"
	.string "... ... ...\p"
	.string "... ... ...\n"
	.string "Inciampai sul mio stesso piede\p"
    .string "la testa mi finì su un sasso\n"
    .string "Dall'ora non so più chi sono\p"
    .string "Ehm ... ... ci lavoro\n"
    .string "giorno dopo giorno... sai...\p"
    .string "va beh\p$"


gText_Birch_MainSpeech::
	.string "Sono stati tempi difficili\n"
	.string "qui, poi essendo l'unico\p"
	.string "ricercatore... è difficile.\n"
    .string "Fuso m'ha aiutato, spesso\p"
	.string "a liberare i POKèMON nel prato\n"
	.string "tempo fa..., dopo sai...\p"
	.string "Però ad alcune persone non gli è\n"
	.string "piaciuta la cosa, perchè...\p"
	.string "aspetta un attimo...\p$"

gText_Birch_AndYouAre::
	.string "Ah si... dimenticavo\p$"

gText_Birch_BoyOrGirl::
	.string "Da protocollo dovresti rispondermi\n"
    .string "ad una serie di domande... tipo\p"
    .string "vorresti le tette qui?\n"
    .string "Seleziona GIRL sennò BOY?$"

gText_Birch_WhatsYourName::
	.string "Perfetto...\n"
	.string "Come vuole essere chiamata?$"

gText_Birch_SoItsPlayer::
	.string "allora ti \n"
    .string "chiamerò {PLAYER}{KUN}...$"

gText_Birch_YourePlayer::
	.string "Hey Prillìcius\n"
    .string "Da dove sbuchi?!?\p"
    .string "Va beh... comunque\n"
	.string "Senti ho chiamato\p"
	.string "JENNY che ti ospiterà a\n"
	.string "casa sua, è il primo posto\p"
	.string "libero che ho trovato\n"
	.string "Fattelo andare bene.\p$"

gText_Birch_AreYouReady::
	.string "POWN ... ... .,\n"
	.string "... ... ... ... .\p"
	.string "Si, rimpicciolisci AHAHAHA\n"
	.string "Quanto amo la Scienza ihiihi\p$"
