gText_Birch_Welcome::
	.string "Hey, da quanto tempo\n"
	.string "allora come va?\p"
	.string "Sai qualche giorno fa\n"
	.string "è passato Fuso... m'ha detto\l"
	.string "che saresti passat'\p$"

gText_Birch_Pokemon::
    .string "Questa è Prilliciius.\n"
    .string "Sai mi fa compania da\l"
    .string "quella volta...\p"
	.string "Era sera, non so se ricordi\n"
	.string "c'era Fuso con GucciMane che si\l"
	.string "facevano di eroina al centro...\p"
	.string "io ero ubriaco e ho sbattuto\n"
	.string "la testa, da li non so\l"
    .string "più chi sono, ci lavoro\l"
    .string "giorno dopo giorno... sai...\l"
    .string "va beh\p$"


gText_Birch_MainSpeech::
	.string "Sono stati tempi difficili\n"
	.string "qui, sai essendo l'unico\l"
	.string "ricercatore...\p"
    .string "Fuso mi ha aiutato, spesso\n"
	.string "a liberare i POKèMON nel prato\l"
	.string "tempo fa...\p"
	.string "Però ad alcune persone non gli è\n"
	.string "piaciuta la cosa, perchè...\l"
	.string "aspetta un attimo...\p$"

gText_Birch_AndYouAre::
	.string "Ah si... dimenticavo\p$"

gText_Birch_BoyOrGirl::
	.string "Una domanda che ti devo fare\n"
    .string "vorresti le tette qui?\l"
    .string "Seleziona GIRL sennò BOY?$"

gText_Birch_WhatsYourName::
	.string "Perfetto...\n"
	.string "Ora inserisci il tuo ID?$"

gText_Birch_SoItsPlayer::
	.string "Meraviglioso allora ti \n"
    .string "chiamerò {PLAYER}{KUN}, Ok?$"

gText_Birch_YourePlayer::
	.string "Senti ho chiamato\p"
	.string "JENNY che ti ospiterà a\n"
	.string "casa sua, è il primo posto\l"
	.string "libero che ho trovato\p"
	.string "Fattelo andare bene.\p$"

gText_Birch_AreYouReady::
	.string "POWN ...\n"
	.string "... ... ....\p"
	.string "Si, rimpicciolisci AHAHAHA\n"
	.string "Quanto amo la Scienza\p$"
