gText_Birch_Welcome::
	.string "Hey, da quanto tempo\n"
	.string "allora come va?\p"
	.string "Sai qualche giorno fa\n"
	.string "è passato Fuso... m'ha detto\n"
	.string "che saresti passat\p$"

gText_Birch_Pokemon::
    .string "Questa è Prilliciius.\n"
    .string "Sai mi fa compania da\n"
    .string "quella volta...\p"
	.string "Era sera, non so se ricordi\n"
	.string "c'era Fuso con GucciMane che si\n"
	.string "facevano di ero al centro...\p"
	.string "io ero ubriaco e ho sbattuto\n"
	.string "la testa, da li non so\n"
    .string "più chi sono\p\n"
    .string "$"


gText_Birch_MainSpeech::
	.string "Sono stati tempi difficili\n"
	.string "qui, sai essendo l'unico\l"
	.string "ricercatore...\p"
    .string "Fuso mi ha aiutato\n"
	.string "a liberare i POKèMON nel prato\n"
	.string "tempo fa...\p"
	.string "Però ad alcune persone non gli è\n"
	.string "piaciuta la cosa, perchè\l"
	.string "va beh, aspetta un attimo...\p$"

gText_Birch_AndYouAre::
	.string "Ah si... dimenticavo$"

gText_Birch_BoyOrGirl::
	.string "Qui puoi scegliere il tuo avatar\n"
    .string "vorresti le tette?$"

gText_Birch_WhatsYourName::
	.string "Perfetto...\n"
	.string "Ora inserisci il tuo nome\l"
    .string "da BestPlayer$"

gText_Birch_SoItsPlayer::
	.string "Meraviglioso allora ti \n"
    .string "chiamerò {PLAYER}{KUN}, Ok?$"

gText_Birch_YourePlayer::
	.string "Senti abbiamo chiamato\n"
	.string "JENNY che ti ospiterà\n"
	.string "a casa sua, è il primo posto\l"
	.string "libero che ho trovato\n"
	.string "Fattelo andare bene.\p$"

gText_Birch_AreYouReady::
	.string "POWN ...\n"
	.string "... ... ....\p"
	.string "Dai Aprite le porte del camion\p$"
