gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gControlsGuide_Text_DPad::
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gControlsGuide_Text_AButton::
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
    .string "Press this button to open the\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gControlsGuide_Text_LRButtons::
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Scusa Fra ma dopo la bottas\n"
    .string "non ricordo cosa sei?$"

gPikachuIntro_Text_Page1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gPikachuIntro_Text_Page2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gPikachuIntro_Text_Page3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Da quanto vecchio amico\n"
    .string "Allora come va?\p"
    .string "Sai qui solito, è passato Fuso\n"
    .string "che da un botto che non vedevo\n"
    .string "e ora tu, Viva la Figa, comunque\p"
    .string "Ti Ricordi i POKèMON?\p$"

gOakSpeech_Text_ThisWorld::
    .string "HAHAHAHHAHA…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…Lei è Prupillis\n"
    .string "La mia POKèMON hihi$"

gOakSpeech_Text_IStudyPokemon::
    .string "Sai dopo quell'evento\n"
    .string "non so se ricordi...\p"
    .string "Quando GucciMane si stava facendo di ERO\ncon Fuso\p"
    .string "Io ero ubriaco e ho sbattuto la testa$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "va beh dai... Prupillis torna dentro$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Uuuuuiii DOOM ...\n"
    .string "... DOOM ... DOM\n"
    .string "Alla ricerca della Figa$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Ah è vero\n"
    .string "tu chiami {PLAYER}, ora ricordo$"

gOakSpeech_Text_WhatWasHisName::
    .string "Invece lui è il tuo amico\p"
    .string "non ricordo il nome,\n"
    .string "ma quella sera c'era.\p"
    .string "lo chiamavate Er Coatto\n"
    .string "come si chiama?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Aia zio cane il mignolo!$"

gOakSpeech_Text_ConfirmRivalName::
    .string "Cosa?? {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "Beh arriverà {RIVAL}\nfra qualche giorno$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Ricorda...\nQuando fai la mista\p"
    .string "Devi staccare una cimetta\n"
    .string "o un cicinin di fiumello\n"
    .string "e metterlo da parte...\n"
    .string "SEMPRE... SEMPRE$"
