gText_ObtainedTheItem::
	.string "Obtained the {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Spiaze il BAG è full.$"

gText_PutItemInPocket::
	.string "{PLAYER} mette {STR_VAR_2}\n"
	.string "nel {STR_VAR_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} ha trovato {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Spiaze\n"
	.string "il BAG è full...$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} mette {STR_VAR_2}\n"
	.string "nel BAG.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "non c'è spazio\n"
	.string "{STR_VAR_2} non ci stà...$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} AVVIO SSH connection...\n"
	.string "traferimento in corso...$"
