Text_BootUpPC:
	.string "{PLAYER} Collegato\n"
    .string "Chrome incognito attivo$"

gText_WhichPCShouldBeAccessed::
	.string "A cosa vuoi accedere?$"

gText_AccessedSomeonesPC::
	.string "Accesso 200 SOMEONE'S PC.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System operto.$"

gText_AccessedPlayersPC::
	.string "Accesso 200 {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Accesso 200 TIZIO STRANO's PC.$"
