Text_MayIHelpYou::
	.string "Hey Fra!, allora?$"

Text_FillOutQuestionnaire::
	.string "Schedina?\n"

Text_QuestionnaireThankYou::
	.string "hahah ci sei cascato\n"
	.string "Coglione$"

Text_YouKnowThoseWords::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY GIFT.\p"
	.string "From now on, you should be\n"
	.string "receiving MYSTERY GIFTS!$"

Text_YouCanAccessMysteryGift::
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY GIFT.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Thank you for accessing the\n"
	.string "MYSTERY GIFT System.$"
