gText_WouldYouLikeToSaveTheGame::
	.string "Ti piacerebbe ricordarti\n"
    .string "la tua vita fino a questo punto?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Ti salvando i dati nella testa, {PLAYER}?$"

gText_SavingDontTurnOffThePower::
	.string "Non muoverti$"

gText_PlayerSavedTheGame::
	.string "Fatto {PLAYER}, ora ti ricorderai$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "POKéMON, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"
