	.align 2
gText_ConfirmSave::
	.string "Vuoi Ricordarti$"

gText_AlreadySavedFile::
	.string "Un momento?$"

gText_SavingDontTurnOff::
	.string "3... 2... 1$"

gText_PlayerSavedGame::
	.string "Fatto, vai pure {PLAYER}$"

gText_DifferentSaveFile::
	.string "$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "$"
