OldaleTown_House2_MapScripts::
	.byte 0

OldaleTown_House2_EventScript_Woman::
	msgbox OldaleTown_House2_Text_PokemonLevelUp, MSGBOX_NPC
	end

OldaleTown_House2_EventScript_Man::
	msgbox OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon, MSGBOX_NPC
	end

OldaleTown_House2_Text_PokemonLevelUp:
	.string "Sai in Bevo tanto...\n"
	.string "Ho i fantasmi nella testa.$"

OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon:
	.string "Fuso quando stava liberando MEWTWO\n"
	.string "era con il Prof ed è successo qualcosa.$"

