PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: {PLAYER}?\n"
    .string "$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: Hey Prof, \nperche c'hai chiamato?\n$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: Cazzo\nmi sto cagando addosso$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Heh, I don't need to be\n"
    .string "greedy like you. I'm mature!\p"
    .string "Go ahead and choose, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: Allora prenderò lui$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} a ricevuto {STR_VAR_1}\n"
    .string "dal Prof$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: My POKéMON looks a lot\n"
    .string "tougher than yours.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "Il mio POKèMON vuole lottare\p"
    .string "Vuoi fare un allenamento {PLAYER}?$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "WHAT?\n"
    .string "Unbelievable!\l"
    .string "I picked the wrong POKéMON!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: Yeah!\n"
    .string "Am I great or what?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: hahah forte!\n"
    .string "Beh si pestano questi qua, ahaha\p"
    .string "eh {PLAYER}, no?, ora vado\n"
    .string "piu veloce della luce$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: ECCOMI!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: Ho portato le chiavi...\n"
    .string "Hey cosa sono quelli?$n"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: Ci vediamo {PLAYER}$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER} ci vediamo in giro\n"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "OAK: {RIVAL}?\n"
    .string "Ciao ragazzi, allora...\p"
    .string "ho trovato queste 3 bestie fuori\n"
    .string "Dovevate vederli, hanno talento\p"
    .string "e visto che so che vi piace allenare\n"
    .string "Combattenti, quindi se vi va Haha\p"
    .string "Potete prenderne uno a testa\n"
    .string "Occhio però, uno è un pò così\p"
    .string "è un po lunatico\n"
    .string "Beh comunque, sono sul tavolo\p"
    .string "Poi {PLAYER}, Vammi a prendere un\n"
    .string "pacco alla città accanto$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "OAK: Si c'è un virus che circola, {RIVAL}$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "OAK: Now, {PLAYER}.\p"
    .string "Inside those three POKé BALLS are\n"
    .string "POKéMON.\p"
    .string "Which one will you choose for\n"
    .string "yourself?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "OAK: Hey!\n"
    .string "Don't go away yet!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Pokemon A, .\n"
    .string "\p"
    .string "So, {PLAYER}\n"
    .string "$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Pokemon B, .\n"
    .string "\p"
    .string "So, {PLAYER}\n"
    .string "$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "Pokemon C, .\n"
    .string "\p"
    .string "So, {PLAYER}\n"
    .string "$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "This POKéMON is really quite\n"
    .string "energetic!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "OAK: Predine cura {PLAYER},\n"
    .string "Sai hai preso il testina ahaha$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "OAK: Cazzo ci fai ancora qui\n"
    .string "corri coglione$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "OAK: Oh, {PLAYER}!\p"
    .string "ho sentito {RIVAL}\n"
    .string "dorebbe arrivare fra poco\n"
    .string "sono arrivate le POKèBALLs$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} da pacco a OAK$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Ah! Grazie {PLAYER}\n"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "OAK: Se volete potete\n"
    .string "completarlo però sarà lunga$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "Invece qui c'è un regalo\n"
    .string "da parte di Fuso\p"
    .string "questi sono POKEDEX\n"
    .string "Mi ha aiutato a progettarlo\p"
    .string "Però ora serve fare\nraccolta dati$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: {PLAYER} and {RIVAL}.\n"
    .string "Ecco qui, a voi..., dai ora\nfouri dalle palle$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} ora hai il POKéDEX, non perderlo...\n"
    .string "$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: Quando incontrerai un POKèMON\n"
    .string "Il POKEDEX salverà le Info$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} ora hai anche 5 POKéBALLS.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "Quindi poi fatemi sapere...$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "Dai andate! via$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "POKéMON around the world wait for\n"
    .string "you, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "How is your POKéDEX shaping up?\p"
    .string "{RIVAL} has already caught some\n"
    .string "POKéMON and added to the data.\p"
    .string "So, {PLAYER}, let's have a look at\n"
    .string "your POKéDEX.\p"
    .string "…What's the matter?\n"
    .string "You've added no new data at all.\p"
    .string "I'll give you these, so do try a\n"
    .string "little harder.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Come see me sometime.\p"
    .string "After all, I want to know how your\n"
    .string "POKéDEX is coming along.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "It's like an encyclopedia, but the\n"
    .string "pages are blank.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Those are POKé BALLS.\n"
    .string "They contain POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "That's PROF. OAK's last POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Press START to open the MENU!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "The SAVE option is on the MENU.\n"
    .string "Use it regularly.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "All POKéMON types have strong and\n"
    .string "weak points against others.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "There's an e-mail message here.\p"
    .string "…\p"
    .string "Finally!\n"
    .string "The ultimate TRAINERS of the\l"
    .string "POKéMON LEAGUE are ready to\l"
    .string "take on all comers!\p"
    .string "Bring your best POKéMON and see\n"
    .string "how you rate as a TRAINER!\p"
    .string "POKéMON LEAGUE HQ\n"
    .string "INDIGO PLATEAU\p"
    .string "PROF. OAK, please visit us!\n"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Mi piacciono i POKèMON$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hi, {PLAYER}. I bet you've become\n"
    .string "good friends with your POKéMON.\p"
    .string "By the way, did you know about\n"
    .string "DAISY?\p"
    .string "If you show DAISY your POKéMON,\n"
    .string "she can tell how much it likes you.\p"
    .string "Occasionally, she will even groom\n"
    .string "a POKéMON for you.\p"
    .string "This is a secret, so please don't\n"
    .string "tell anyone.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "PROF. OAK is going to have his own\n"
    .string "radio show soon.\p"
    .string "The program will be called PROF.\n"
    .string "OAK's POKéMON SEMINAR.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "Ciao amore come stai??\n"
    .string "Mi libero per le 18H se vuoi..$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, now this is excellent!\p"
    .string "{PLAYER}, I have another important\n"
    .string "favor to ask of you.\p"
    .string "I need you to listen closely.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Recently, there have been sightings\n"
    .string "of many rare POKéMON species.\p"
    .string "I'm talking about POKéMON that\n"
    .string "have never been seen in KANTO.\p"
    .string "I would love to go see things for\n"
    .string "myself, but I'm much too old.\p"
    .string "Since I can't do it, {PLAYER}, I'd\n"
    .string "like you to go in my place.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey, I heard that!\p"
    .string "Gramps, what's with favoring\n"
    .string "{PLAYER} over me all the time?\p"
    .string "I went and collected more POKéMON,\n"
    .string "and faster, too.\p"
    .string "You should just let me handle\n"
    .string "everything.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: I know, I know.\n"
    .string "Of course I need your help, too.\p"
    .string "Now, I need to see both your\n"
    .string "POKéDEXES.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. OAK took both POKéDEX\n"
    .string "units.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…And that's done!\p"
    .string "Now these units can record data on\n"
    .string "a lot more POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}'s POKéDEX was upgraded!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Now, {PLAYER} and {RIVAL}!\p"
    .string "This time, you really must work\n"
    .string "towards filling your POKéDEXES.\p"
    .string "I urge you to make them the best\n"
    .string "and the most complete of all time!\p"
    .string "Truly, this is a monumentally great\n"
    .string "undertaking in POKéMON history!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Gramps, calm down.\n"
    .string "Don't get so excited.\p"
    .string "I'll get the POKéDEX completed,\n"
    .string "don't you worry about a thing.\p"
    .string "I think I'll try looking around\n"
    .string "ONE ISLAND first…\p"
    .string "Anyways, I'm outta here!$"

