Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "Sono Albert\p"
    .string "Sono un mercante\n"
    .string "Lavoravo sul 9, sai...\p"
    .string "Tieni$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} metti POTION Nel BAG$"

Route1_Text_CanJumpFromLedges::
    .string "il Grande Fuso m'ha dato\n"
    .string "i numeri vincenti alla lotteria\p"
    .string "Tieni poraccio...$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"

