PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "JENNY: Ti sta cercando un tizio\n"
    .string "Ricordati la droga$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "JENNY: ...IXXX.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "JENNY: {PLAYER}!\n"
    .string "Due tiri?$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "JENNY: Dormi {PLAYER}\l"
    .string "Yeah$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Ci sono le coppie\nche litigano in TV.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Ci sono le coppie\nche litigano in TV$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Ndo vai??$"

