ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "{PLAYER} vieni vieni$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "Porta questo a OAK\n"
    .string "che m'ha detto\nche passavi oggi$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} ricevi PACCO OAK'S$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Salutami il volpone\n"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "LEOTTA: Tieni Ammore, dallo ai tuoi\n"
    .string "POKèMON$"

ViridianCity_Mart_Text_DonationPotion::
    .string "{PLAYER} riceve POTION da Leotta$"


ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "Ahahaha ti sono caduti dei soldi.$"

